spring:
  ai:
    openai:
      api-key: ${AI_API_KEY}
  application:
    name: maki_test
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/local?authSource=admin
      database: local
springdoc:
  api-docs:
    enabled: true